-- Start of generated script for 10.255.254.5-yktinst1-YKTBASE (yktinst1)
--  May-08-2008 at 10:34:31

#QSCOMMAND EXPORT TO '%DATA_PATH%\YKTBASE.YKT_CUR.T_CUSTOMERTMP.9.1\T_CUSTOMERTMP.ixf'
  OF IXF
  SELECT * FROM YKT_CUR.T_CUSTOMERTMP;

#SYNC 10;

DROP TABLE YKT_CUR.T_CUSTOMERTMP;

#SYNC 20;

CREATE TABLE YKT_CUR.T_CUSTOMERTMP
 (STUEMP_NO         VARCHAR(30)     NOT NULL,
  CUT_NAME          VARCHAR(60),
  CUT_TYPE          INTEGER,
  SEX               CHARACTER(1),
  ID_TYPE           INTEGER,
  ID_NO             VARCHAR(60),
  COUNTRY           VARCHAR(30),
  PEOPLE            INTEGER,
  ADDR              VARCHAR(240),
  TEL               VARCHAR(30),
  EMAIL             VARCHAR(60),
  AREA_NO           INTEGER,
  DEPT_NO           VARCHAR(30),
  SPECIALTY_NO      VARCHAR(30),
  CLASS_NO          VARCHAR(30),
  AT_SCHOOL_STATUS  CHARACTER(1),
  IN_SCHOOL_DATE    CHARACTER(8),
  OUT_SCHOOL_DATE   CHARACTER(8),
  IMP_DATE          CHARACTER(8),
  IMP_OPER          VARCHAR(10),
  IMP_SEQNO         INTEGER,
  IMP_BATCHNO       VARCHAR(30),
  IMP_STATUS        CHARACTER(1)
 )
  DATA CAPTURE NONE
  IN BASEDATA
  INDEX IN BASEINDEX;

#SYNC 30;

ALTER TABLE YKT_CUR.T_CUSTOMERTMP
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

#SYNC 40;

COMMENT ON YKT_CUR.T_CUSTOMERTMP
 (STUEMP_NO IS '学号/工号',
  CUT_NAME IS '姓名',
  CUT_TYPE IS '客户类别',
  SEX IS '性别',
  ID_TYPE IS '证件类型',
  ID_NO IS '证件号码',
  COUNTRY IS '国籍',
  PEOPLE IS '民族',
  ADDR IS '地址',
  TEL IS '电话',
  EMAIL IS '电子信箱',
  AREA_NO IS '校区',
  DEPT_NO IS '部门编号',
  SPECIALTY_NO IS '专业编号',
  CLASS_NO IS '班级编号',
  AT_SCHOOL_STATUS IS '在校状态',
  IN_SCHOOL_DATE IS '入校日期',
  OUT_SCHOOL_DATE IS '离校日期',
  IMP_DATE IS '导入日期',
  IMP_OPER IS '导入操作员',
  IMP_SEQNO IS '导入流水号',
  IMP_BATCHNO IS '导入批次号',
  IMP_STATUS IS '导入状态'
 );

#SYNC 50;

GRANT SELECT ON TABLE YKT_CUR.T_CUSTOMERTMP TO USER YKT_CUR;

GRANT INSERT ON TABLE YKT_CUR.T_CUSTOMERTMP TO USER YKT_CUR;

GRANT UPDATE ON TABLE YKT_CUR.T_CUSTOMERTMP TO USER YKT_CUR;

GRANT DELETE ON TABLE YKT_CUR.T_CUSTOMERTMP TO USER YKT_CUR;

#SYNC 60;

#QSCOMMAND IMPORT FROM '%DATA_PATH%\YKTBASE.YKT_CUR.T_CUSTOMERTMP.9.1\T_CUSTOMERTMP.ixf'
  OF IXF
  MODIFIED BY COMPOUND=5
              NOCHECKLENGTHS
  COMMITCOUNT 1000
--RESTARTCOUNT xxx
  INSERT
  INTO YKT_CUR.T_CUSTOMERTMP;

#SYNC 70;

CREATE INDEX YKT_CUR.IDX_IMP
  ON YKT_CUR.T_CUSTOMERTMP
 (IMP_DATE   ASC,
  IMP_OPER   ASC,
  IMP_SEQNO  ASC
 )
  PCTFREE 10
  ALLOW REVERSE SCANS;

#SYNC 80;

ALTER TABLE YKT_CUR.T_CUSTOMERTMP
  ADD CONSTRAINT SQL080508100725350 PRIMARY KEY
   (STUEMP_NO
   );

#SYNC 90;

RUNSTATS ON TABLE YKT_CUR.T_CUSTOMERTMP
  AND INDEXES ALL 
  SHRLEVEL REFERENCE;

#SYNC 100;



-- End of generated script for 10.255.254.5-yktinst1-YKTBASE (yktinst1)