-- Start of generated script for 10.255.254.5-yktinst1-YKTBASE (yktinst1)
--  May-08-2008 at 10:29:07

GRANT CONNECT ON DATABASE TO USER ykt_cur;

GRANT USE OF TABLESPACE BASEDATA TO USER YKT_CUR;

GRANT SELECT ON TABLE YKT_CUR.T_CUSTOMERTMP TO USER ykt_cur;

GRANT INSERT ON TABLE YKT_CUR.T_CUSTOMERTMP TO USER ykt_cur;

GRANT UPDATE ON TABLE YKT_CUR.T_CUSTOMERTMP TO USER ykt_cur;

GRANT DELETE ON TABLE YKT_CUR.T_CUSTOMERTMP TO USER ykt_cur;

GRANT SELECT ON TABLE YKT_CUR.V_PHOTO TO USER ykt_cur;

GRANT SELECT ON TABLE YKT_CUR.V_CUSTOMER TO USER ykt_cur;

GRANT SELECT ON TABLE YKT_CUR.T_PIF_CARD TO USER YKT_CUR;

GRANT ALTER ON TABLE YKT_CUR.T_PIF_CARD TO USER YKT_CUR;

#SYNC 10;



-- End of generated script for 10.255.254.5-yktinst1-YKTBASE (yktinst1)