//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace UamWebService.damAsset {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="damAssetServiceSoap11Binding", Namespace="http://dam.imc.h3c.com/damAssetService")]
    public partial class damAssetService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback queryAssetGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback addAssetOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryAssetDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryAssetOperationCompleted;
        
        private System.Threading.SendOrPostCallback modifyAssetOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteAssetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public damAssetService() {
            this.Url = global::UamWebService.Properties.Settings.Default.UamWebService_damAsset_damAssetService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event queryAssetGroupCompletedEventHandler queryAssetGroupCompleted;
        
        /// <remarks/>
        public event addAssetCompletedEventHandler addAssetCompleted;
        
        /// <remarks/>
        public event queryAssetDetailCompletedEventHandler queryAssetDetailCompleted;
        
        /// <remarks/>
        public event queryAssetCompletedEventHandler queryAssetCompleted;
        
        /// <remarks/>
        public event modifyAssetCompletedEventHandler modifyAssetCompleted;
        
        /// <remarks/>
        public event deleteAssetCompletedEventHandler deleteAssetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryAssetGroup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryAssetGroupResponse", Namespace="http://dam.imc.h3c.com/damAssetService")]
        public queryAssetGroupResponse queryAssetGroup() {
            object[] results = this.Invoke("queryAssetGroup", new object[0]);
            return ((queryAssetGroupResponse)(results[0]));
        }
        
        /// <remarks/>
        public void queryAssetGroupAsync() {
            this.queryAssetGroupAsync(null);
        }
        
        /// <remarks/>
        public void queryAssetGroupAsync(object userState) {
            if ((this.queryAssetGroupOperationCompleted == null)) {
                this.queryAssetGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryAssetGroupOperationCompleted);
            }
            this.InvokeAsync("queryAssetGroup", new object[0], this.queryAssetGroupOperationCompleted, userState);
        }
        
        private void OnqueryAssetGroupOperationCompleted(object arg) {
            if ((this.queryAssetGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryAssetGroupCompleted(this, new queryAssetGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:addAsset", RequestNamespace="http://dam.imc.h3c.com/damAssetService", ResponseNamespace="http://dam.imc.h3c.com/damAssetService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public WSCommonResult addAsset([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AddAssetInfo param0) {
            object[] results = this.Invoke("addAsset", new object[] {
                        param0});
            return ((WSCommonResult)(results[0]));
        }
        
        /// <remarks/>
        public void addAssetAsync(AddAssetInfo param0) {
            this.addAssetAsync(param0, null);
        }
        
        /// <remarks/>
        public void addAssetAsync(AddAssetInfo param0, object userState) {
            if ((this.addAssetOperationCompleted == null)) {
                this.addAssetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddAssetOperationCompleted);
            }
            this.InvokeAsync("addAsset", new object[] {
                        param0}, this.addAssetOperationCompleted, userState);
        }
        
        private void OnaddAssetOperationCompleted(object arg) {
            if ((this.addAssetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addAssetCompleted(this, new addAssetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryAssetDetail", RequestNamespace="http://dam.imc.h3c.com/damAssetService", ResponseNamespace="http://dam.imc.h3c.com/damAssetService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public RetAssetDetailInfo queryAssetDetail(long param0, [System.Xml.Serialization.XmlIgnoreAttribute()] bool param0Specified) {
            object[] results = this.Invoke("queryAssetDetail", new object[] {
                        param0,
                        param0Specified});
            return ((RetAssetDetailInfo)(results[0]));
        }
        
        /// <remarks/>
        public void queryAssetDetailAsync(long param0, bool param0Specified) {
            this.queryAssetDetailAsync(param0, param0Specified, null);
        }
        
        /// <remarks/>
        public void queryAssetDetailAsync(long param0, bool param0Specified, object userState) {
            if ((this.queryAssetDetailOperationCompleted == null)) {
                this.queryAssetDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryAssetDetailOperationCompleted);
            }
            this.InvokeAsync("queryAssetDetail", new object[] {
                        param0,
                        param0Specified}, this.queryAssetDetailOperationCompleted, userState);
        }
        
        private void OnqueryAssetDetailOperationCompleted(object arg) {
            if ((this.queryAssetDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryAssetDetailCompleted(this, new queryAssetDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryAsset", RequestNamespace="http://dam.imc.h3c.com/damAssetService", ResponseNamespace="http://dam.imc.h3c.com/damAssetService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public RetAssetInfoList queryAsset([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AssetQueryInfo param0) {
            object[] results = this.Invoke("queryAsset", new object[] {
                        param0});
            return ((RetAssetInfoList)(results[0]));
        }
        
        /// <remarks/>
        public void queryAssetAsync(AssetQueryInfo param0) {
            this.queryAssetAsync(param0, null);
        }
        
        /// <remarks/>
        public void queryAssetAsync(AssetQueryInfo param0, object userState) {
            if ((this.queryAssetOperationCompleted == null)) {
                this.queryAssetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryAssetOperationCompleted);
            }
            this.InvokeAsync("queryAsset", new object[] {
                        param0}, this.queryAssetOperationCompleted, userState);
        }
        
        private void OnqueryAssetOperationCompleted(object arg) {
            if ((this.queryAssetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryAssetCompleted(this, new queryAssetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:modifyAsset", RequestNamespace="http://dam.imc.h3c.com/damAssetService", ResponseNamespace="http://dam.imc.h3c.com/damAssetService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public WSCommonResult modifyAsset([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ModifyAssetInfo param0) {
            object[] results = this.Invoke("modifyAsset", new object[] {
                        param0});
            return ((WSCommonResult)(results[0]));
        }
        
        /// <remarks/>
        public void modifyAssetAsync(ModifyAssetInfo param0) {
            this.modifyAssetAsync(param0, null);
        }
        
        /// <remarks/>
        public void modifyAssetAsync(ModifyAssetInfo param0, object userState) {
            if ((this.modifyAssetOperationCompleted == null)) {
                this.modifyAssetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodifyAssetOperationCompleted);
            }
            this.InvokeAsync("modifyAsset", new object[] {
                        param0}, this.modifyAssetOperationCompleted, userState);
        }
        
        private void OnmodifyAssetOperationCompleted(object arg) {
            if ((this.modifyAssetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modifyAssetCompleted(this, new modifyAssetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:deleteAsset", RequestNamespace="http://dam.imc.h3c.com/damAssetService", ResponseNamespace="http://dam.imc.h3c.com/damAssetService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public WSCommonResult deleteAsset(long param0, [System.Xml.Serialization.XmlIgnoreAttribute()] bool param0Specified) {
            object[] results = this.Invoke("deleteAsset", new object[] {
                        param0,
                        param0Specified});
            return ((WSCommonResult)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAssetAsync(long param0, bool param0Specified) {
            this.deleteAssetAsync(param0, param0Specified, null);
        }
        
        /// <remarks/>
        public void deleteAssetAsync(long param0, bool param0Specified, object userState) {
            if ((this.deleteAssetOperationCompleted == null)) {
                this.deleteAssetOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteAssetOperationCompleted);
            }
            this.InvokeAsync("deleteAsset", new object[] {
                        param0,
                        param0Specified}, this.deleteAssetOperationCompleted, userState);
        }
        
        private void OndeleteAssetOperationCompleted(object arg) {
            if ((this.deleteAssetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteAssetCompleted(this, new deleteAssetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dam.imc.h3c.com/damAssetService")]
    public partial class queryAssetGroupResponse {
        
        private RetAssetGroupInfoList returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RetAssetGroupInfoList @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asset.damws.imc.h3c.com/xsd")]
    public partial class RetAssetGroupInfoList : WSCommonResult {
        
        private RetAssetGroupInfo[] retAssetGroupInfoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("retAssetGroupInfoList", IsNullable=true)]
        public RetAssetGroupInfo[] retAssetGroupInfoList {
            get {
                return this.retAssetGroupInfoListField;
            }
            set {
                this.retAssetGroupInfoListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asset.damws.imc.h3c.com/xsd")]
    public partial class RetAssetGroupInfo {
        
        private string groupDescriptionField;
        
        private System.Nullable<long> groupIdField;
        
        private bool groupIdFieldSpecified;
        
        private string groupNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string groupDescription {
            get {
                return this.groupDescriptionField;
            }
            set {
                this.groupDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupIdSpecified {
            get {
                return this.groupIdFieldSpecified;
            }
            set {
                this.groupIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asset.damws.imc.h3c.com/xsd")]
    public partial class ModifyAssetInfo {
        
        private System.Nullable<long> assetIdField;
        
        private bool assetIdFieldSpecified;
        
        private string assetNameField;
        
        private string assetNumberField;
        
        private string computerTypeField;
        
        private string computerVarietyField;
        
        private string physicalPosField;
        
        private string remarkField;
        
        private System.Nullable<long> responserIdField;
        
        private bool responserIdFieldSpecified;
        
        private long serialVersionUIDField;
        
        private bool serialVersionUIDFieldSpecified;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> assetId {
            get {
                return this.assetIdField;
            }
            set {
                this.assetIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool assetIdSpecified {
            get {
                return this.assetIdFieldSpecified;
            }
            set {
                this.assetIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string assetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string assetNumber {
            get {
                return this.assetNumberField;
            }
            set {
                this.assetNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string computerType {
            get {
                return this.computerTypeField;
            }
            set {
                this.computerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string computerVariety {
            get {
                return this.computerVarietyField;
            }
            set {
                this.computerVarietyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string physicalPos {
            get {
                return this.physicalPosField;
            }
            set {
                this.physicalPosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> responserId {
            get {
                return this.responserIdField;
            }
            set {
                this.responserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responserIdSpecified {
            get {
                return this.responserIdFieldSpecified;
            }
            set {
                this.responserIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long serialVersionUID {
            get {
                return this.serialVersionUIDField;
            }
            set {
                this.serialVersionUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serialVersionUIDSpecified {
            get {
                return this.serialVersionUIDFieldSpecified;
            }
            set {
                this.serialVersionUIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asset.damws.imc.h3c.com/xsd")]
    public partial class AssetQueryInfo {
        
        private string assetNameField;
        
        private string assetNumberField;
        
        private string computerTypeField;
        
        private string computerVarietyField;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private bool endDateFieldSpecified;
        
        private System.Nullable<long> groupIdField;
        
        private bool groupIdFieldSpecified;
        
        private string operSystemField;
        
        private System.Nullable<int> operSystemIdField;
        
        private bool operSystemIdFieldSpecified;
        
        private string operSystemMendField;
        
        private string responserField;
        
        private System.Nullable<int> resultIndexField;
        
        private bool resultIndexFieldSpecified;
        
        private System.Nullable<int> resultNumberField;
        
        private bool resultNumberFieldSpecified;
        
        private System.Nullable<int> resultSortField;
        
        private bool resultSortFieldSpecified;
        
        private System.Nullable<int> resultSortTypeField;
        
        private bool resultSortTypeFieldSpecified;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.Nullable<int> statusField;
        
        private bool statusFieldSpecified;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string assetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string assetNumber {
            get {
                return this.assetNumberField;
            }
            set {
                this.assetNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string computerType {
            get {
                return this.computerTypeField;
            }
            set {
                this.computerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string computerVariety {
            get {
                return this.computerVarietyField;
            }
            set {
                this.computerVarietyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupIdSpecified {
            get {
                return this.groupIdFieldSpecified;
            }
            set {
                this.groupIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string operSystem {
            get {
                return this.operSystemField;
            }
            set {
                this.operSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> operSystemId {
            get {
                return this.operSystemIdField;
            }
            set {
                this.operSystemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operSystemIdSpecified {
            get {
                return this.operSystemIdFieldSpecified;
            }
            set {
                this.operSystemIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string operSystemMend {
            get {
                return this.operSystemMendField;
            }
            set {
                this.operSystemMendField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string responser {
            get {
                return this.responserField;
            }
            set {
                this.responserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> resultIndex {
            get {
                return this.resultIndexField;
            }
            set {
                this.resultIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultIndexSpecified {
            get {
                return this.resultIndexFieldSpecified;
            }
            set {
                this.resultIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> resultNumber {
            get {
                return this.resultNumberField;
            }
            set {
                this.resultNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultNumberSpecified {
            get {
                return this.resultNumberFieldSpecified;
            }
            set {
                this.resultNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> resultSort {
            get {
                return this.resultSortField;
            }
            set {
                this.resultSortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultSortSpecified {
            get {
                return this.resultSortFieldSpecified;
            }
            set {
                this.resultSortFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> resultSortType {
            get {
                return this.resultSortTypeField;
            }
            set {
                this.resultSortTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultSortTypeSpecified {
            get {
                return this.resultSortTypeFieldSpecified;
            }
            set {
                this.resultSortTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asset.damws.imc.h3c.com/xsd")]
    public partial class AddAssetInfo {
        
        private string assetNameField;
        
        private string assetNumberField;
        
        private string computerTypeField;
        
        private string computerVarietyField;
        
        private System.Nullable<long> groupIdField;
        
        private bool groupIdFieldSpecified;
        
        private string physicalPosField;
        
        private string remarkField;
        
        private System.Nullable<long> responserIdField;
        
        private bool responserIdFieldSpecified;
        
        private long serialVersionUIDField;
        
        private bool serialVersionUIDFieldSpecified;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string assetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string assetNumber {
            get {
                return this.assetNumberField;
            }
            set {
                this.assetNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string computerType {
            get {
                return this.computerTypeField;
            }
            set {
                this.computerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string computerVariety {
            get {
                return this.computerVarietyField;
            }
            set {
                this.computerVarietyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupIdSpecified {
            get {
                return this.groupIdFieldSpecified;
            }
            set {
                this.groupIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string physicalPos {
            get {
                return this.physicalPosField;
            }
            set {
                this.physicalPosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> responserId {
            get {
                return this.responserIdField;
            }
            set {
                this.responserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responserIdSpecified {
            get {
                return this.responserIdFieldSpecified;
            }
            set {
                this.responserIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long serialVersionUID {
            get {
                return this.serialVersionUIDField;
            }
            set {
                this.serialVersionUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serialVersionUIDSpecified {
            get {
                return this.serialVersionUIDFieldSpecified;
            }
            set {
                this.serialVersionUIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asset.damws.imc.h3c.com/xsd")]
    public partial class RetAssetInfo {
        
        private System.Nullable<long> assetIdField;
        
        private bool assetIdFieldSpecified;
        
        private string assetNameField;
        
        private string assetNumberField;
        
        private System.Nullable<long> groupIdField;
        
        private bool groupIdFieldSpecified;
        
        private System.Nullable<System.DateTime> joinDateField;
        
        private bool joinDateFieldSpecified;
        
        private string responserField;
        
        private System.Nullable<int> statusField;
        
        private bool statusFieldSpecified;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> assetId {
            get {
                return this.assetIdField;
            }
            set {
                this.assetIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool assetIdSpecified {
            get {
                return this.assetIdFieldSpecified;
            }
            set {
                this.assetIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string assetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string assetNumber {
            get {
                return this.assetNumberField;
            }
            set {
                this.assetNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupIdSpecified {
            get {
                return this.groupIdFieldSpecified;
            }
            set {
                this.groupIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> joinDate {
            get {
                return this.joinDateField;
            }
            set {
                this.joinDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool joinDateSpecified {
            get {
                return this.joinDateFieldSpecified;
            }
            set {
                this.joinDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string responser {
            get {
                return this.responserField;
            }
            set {
                this.responserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetAssetInfoList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetAssetGroupInfoList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetAssetDetailInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.common.imc.h3c.com/xsd")]
    public partial class WSCommonResult {
        
        private string descriptionField;
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asset.damws.imc.h3c.com/xsd")]
    public partial class RetAssetInfoList : WSCommonResult {
        
        private RetAssetInfo[] retAssetListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("retAssetList", IsNullable=true)]
        public RetAssetInfo[] retAssetList {
            get {
                return this.retAssetListField;
            }
            set {
                this.retAssetListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asset.damws.imc.h3c.com/xsd")]
    public partial class RetAssetDetailInfo : WSCommonResult {
        
        private string assetNameField;
        
        private string assetNumberField;
        
        private string computerTypeField;
        
        private string computerVarietyField;
        
        private string groupNameField;
        
        private string physicalPosField;
        
        private string remarkField;
        
        private long responserIdField;
        
        private bool responserIdFieldSpecified;
        
        private string responserNameField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string assetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string assetNumber {
            get {
                return this.assetNumberField;
            }
            set {
                this.assetNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string computerType {
            get {
                return this.computerTypeField;
            }
            set {
                this.computerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string computerVariety {
            get {
                return this.computerVarietyField;
            }
            set {
                this.computerVarietyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string physicalPos {
            get {
                return this.physicalPosField;
            }
            set {
                this.physicalPosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public long responserId {
            get {
                return this.responserIdField;
            }
            set {
                this.responserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responserIdSpecified {
            get {
                return this.responserIdFieldSpecified;
            }
            set {
                this.responserIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string responserName {
            get {
                return this.responserNameField;
            }
            set {
                this.responserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryAssetGroupCompletedEventHandler(object sender, queryAssetGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryAssetGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryAssetGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public queryAssetGroupResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((queryAssetGroupResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void addAssetCompletedEventHandler(object sender, addAssetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addAssetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addAssetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSCommonResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSCommonResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryAssetDetailCompletedEventHandler(object sender, queryAssetDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryAssetDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryAssetDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetAssetDetailInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetAssetDetailInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryAssetCompletedEventHandler(object sender, queryAssetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryAssetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryAssetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetAssetInfoList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetAssetInfoList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void modifyAssetCompletedEventHandler(object sender, modifyAssetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modifyAssetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal modifyAssetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSCommonResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSCommonResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void deleteAssetCompletedEventHandler(object sender, deleteAssetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteAssetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteAssetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSCommonResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSCommonResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591