// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*LCID:00000804:00000804*/ /**/
/*ITE*/ /*DFMFileType*/ /*vcl\NMSHOW.dfm*/
/*ITE*/ /*DFMFileType*/ /*uAuthGroup.dfm*/
/*ITE*/ /*DFMFileType*/ /*uConfigTariff.dfm*/
/*ITE*/ /*DFMFileType*/ /*uFieldValue.dfm*/
/*ITE*/ /*DFMFileType*/ /*uRecordType.dfm*/
/*ITE*/ /*DFMFileType*/ /*uRemoteOpenLock.dfm*/
/*ITE*/ /*DFMFileType*/ /*uSelectFile.dfm*/
/*ITE*/ /*DFMFileType*/ /*uSetAccessTable.dfm*/
/*ITE*/ /*DFMFileType*/ /*uSetCardTime.dfm*/
/*ITE*/ /*DFMFileType*/ /*uSetHolidayRule.dfm*/
/*ITE*/ /*DFMFileType*/ /*uSetJowTime.dfm*/
/*ITE*/ /*DFMFileType*/ /*uSetLockProp.dfm*/
/*ITE*/ /*DFMFileType*/ /*uSetOrganNum.dfm*/
/*ITE*/ /*DFMFileType*/ /*uSetPeriod.dfm*/
/*ITE*/ /*DFMFileType*/ /*uSetRatio.dfm*/
/*ITE*/ /*DFMFileType*/ /*uSetShortcutKey.dfm*/
/*ITE*/ /*DFMFileType*/ /*uSetWorkadayRule.dfm*/
/*ITE*/ /*DFMFileType*/ /*uSignIn.dfm*/
/*ITE*/ /*DFMFileType*/ /*uStart.dfm*/
/*ITE*/ /*DFMFileType*/ /*uTest.dfm*/
/*ITE*/ /*DFMFileType*/ /*uUpdateBCList.dfm*/
/*ITE*/ /*DFMFileType*/ /*uUpdateBCListOfID.dfm*/
/*ITE*/ /*DFMFileType*/ /*uUpdateWCList.dfm*/
/*ITE*/ /*DFMFileType*/ /*uVersion.dfm*/
/*ITE*/ /*RCFileType*/ /*pTest_DRC.rc*/
//---------------------------------------------------------------------------
//USEFORMRES("vcl\NMSHOW.dfm", NMShow, Form); /* Form: DesignClass */
//#pragma resource "vcl\NMSHOW.dfm"
USEFORMRES("uAuthGroup.dfm", frmAuthGroup, Form); /* TForm: DesignClass */
#pragma resource "uAuthGroup.dfm"
USEFORMRES("uConfigTariff.dfm", frmConfigTariff, Form); /* TForm: DesignClass */
#pragma resource "uConfigTariff.dfm"
USEFORMRES("uFieldValue.dfm", frmFieldValue, Form); /* TForm: DesignClass */
#pragma resource "uFieldValue.dfm"
USEFORMRES("uRecordType.dfm", frmRecordType, Form); /* TForm: DesignClass */
#pragma resource "uRecordType.dfm"
USEFORMRES("uRemoteOpenLock.dfm", frmRemoteOpenLock, Form); /* TForm: DesignClass */
#pragma resource "uRemoteOpenLock.dfm"
USEFORMRES("uSelectFile.dfm", frmSelectFile, Form); /* TForm: DesignClass */
#pragma resource "uSelectFile.dfm"
USEFORMRES("uSetAccessTable.dfm", frmSetAccessTable, Form); /* TForm: DesignClass */
#pragma resource "uSetAccessTable.dfm"
USEFORMRES("uSetCardTime.dfm", frmSetCardTime, Form); /* TForm: DesignClass */
#pragma resource "uSetCardTime.dfm"
USEFORMRES("uSetGroupProp.dfm", frmSetGroupProp, Form); /* TForm: DesignClass */
#pragma resource "uSetGroupProp.dfm"
USEFORMRES("uSetHolidayRule.dfm", frmSetHolidayRule, Form); /* TForm: DesignClass */
#pragma resource "uSetHolidayRule.dfm"
USEFORMRES("uSetJowTime.dfm", frmSetJowTime, Form); /* TForm: DesignClass */
#pragma resource "uSetJowTime.dfm"
USEFORMRES("uSetLockProp.dfm", frmSetLockProp, Form); /* TForm: DesignClass */
#pragma resource "uSetLockProp.dfm"
USEFORMRES("uSetOrganNum.dfm", frmSetOrganNum, Form); /* TForm: DesignClass */
#pragma resource "uSetOrganNum.dfm"
USEFORMRES("uSetPeriod.dfm", frmSetPeriod, Form); /* TForm: DesignClass */
#pragma resource "uSetPeriod.dfm"
USEFORMRES("uSetPeriodMode.dfm", frmSetPeriodMode, Form); /* TForm: DesignClass */
#pragma resource "uSetPeriodMode.dfm"
USEFORMRES("uSetRatio.dfm", frmSetRatio, Form); /* TForm: DesignClass */
#pragma resource "uSetRatio.dfm"
USEFORMRES("uSetShortcutKey.dfm", frmSetShortcutKey, Form); /* TForm: DesignClass */
#pragma resource "uSetShortcutKey.dfm"
USEFORMRES("uSetWorkadayRule.dfm", frmSetWorkadayRule, Form); /* TForm: DesignClass */
#pragma resource "uSetWorkadayRule.dfm"
USEFORMRES("uSignIn.dfm", frmSignIn, Form); /* TForm: DesignClass */
#pragma resource "uSignIn.dfm"
USEFORMRES("uStart.dfm", frmStart, Form); /* TForm: DesignClass */
#pragma resource "uStart.dfm"
USEFORMRES("uTest.dfm", frmTest, Form); /* TForm: DesignClass */
#pragma resource "uTest.dfm"
USEFORMRES("uUpdateBCList.dfm", frmUpdateBCList, Form); /* TForm: DesignClass */
#pragma resource "uUpdateBCList.dfm"
USEFORMRES("uUpdateBCListOfID.dfm", frmUpdateBCListOfID, Form); /* TForm: DesignClass */
#pragma resource "uUpdateBCListOfID.dfm"
USEFORMRES("uUpdateWCList.dfm", frmUpdateWCList, Form); /* TForm: DesignClass */
#pragma resource "uUpdateWCList.dfm"
USEFORMRES("uVersion.dfm", frmVersion, Form); /* TForm: DesignClass */
#pragma resource "uVersion.dfm"
USERC("pTest_DRC.rc");
USERES("pTest.res");
//---------------------------------------------------------------------------
#define DllEntryPoint
